site_name: Portal de Ajuda do Josafá

# Repository
repo_url: https://gitlab.com/josalab/ajuda
edit_uri: "edit/main/docs"

# Copyright
copyright: Copyright &copy; 2019 - 2021 Josafá Sisino Machado

# Configuration
theme:
  favicon: imagens/favicon.ico
  logo: imagens/favicon.ico
  name: material
  language: pt

nav:
  - Início: index.md
  - Google:
    - Sala de aula:
      - Acesso: google/sala-de-aula.md
      - Tópicos: google/sala-de-aula/topicos.md
    - Meet:
      - Compartilhar tela: google/meet/compartilhar-tela.md
    - Formulário:
      - Imprimir: google/formulario/imprimir.md
  - Microsoft:
    - Zoom it: 
      - Apresentação: microsoft/zoom-it/apresentacao.md
      - Instalação: microsoft/zoom-it/instalacao.md
      - Ampliação:
        - Congelada: microsoft/zoom-it/ampliacao/congelada.md
        - Interativa: microsoft/zoom-it/ampliacao/interativa.md
      - Desenho: microsoft/zoom-it/desenho.md
  - Padlet:
    - Introdução: padlet/introducao.md
  
  # - Documento : google/documento.md
  # - Planilha: google/planilha.md

# plugins:
#   - awesome-pages
#   - git-revision-date-localized
#   - search

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.tilde
