site_name: Portal de Ajuda do Josafá

# Repository
repo_url: https://gitlab.com/josalab/ajuda
edit_uri: "edit/main/docs"

# Copyright
copyright: Copyright &copy; 2019 - 2021 Josafá Sisino Machado

# Configuration
theme:
  favicon: imagens/favicon.ico
  logo: imagens/favicon.ico
  name: material
  language: pt

nav:
  - Início: index.md
  - Google:
    - Sala de aula: google/sala-de-aula.md
      - Tópicos: google/sala-de-aula/topicos.md
    - Meet:
      - Compartilhar tela: google/meet/compartilhar-tela.md
    - Formulário:
      - Imprimir: google/formulario/imprimir.md
  - Microsoft:
    - Zoom it: microsoft/zoom-it.md
  
  # - Documento : google/documento.md
  # - Planilha: google/planilha.md

